### PR TITLE
Fixed Hebrew missing strings

### PR DESCRIPTION
**Pull request by Eng2Heb**
The original strings.po Herbrew file in Gitahab contains only 501 lines (!).
Therefore I left it behind, and took the English strings.po file and translated it from scratch.
If it still miss a line, please send me the original file to be translated.

### CODE REVIEW

**Comment by Guilouz** [comment]
File to translate is here : https://raw.githubusercontent.com/Guilouz/repository.guilouz/master/skin.estuary.modv2/language/resource.language.en_gb/strings.po

**Comment by Eng2Heb** [comment]
I see the mistake. 
This patch is for the old Estuary Hebrew file (skin.estuary.mod) which I updated and currently use. In address:
https://github.com/Guilouz/repository.guilouz/tree/master/skin.estuary.mod/language/resource.language.he_il
Please merge "Patch 4" it in the old releaase.


I will translate also the "https://raw.githubusercontent.com/Guilouz/repository.guilouz/master/skin.estuary.modv2/language/resource.language.en_gb/strings.po"
later on today.

Thank you.

**Comment by Guilouz** [comment]
File is not full for skin.estuary.mod too...

Development for skin.estuary.mod is ended and I will remove it soon.

But you can send me translation for Estuary MOD V2

**Comment by Eng2Heb** [comment]
1. Estuary MOD V2 - Done.
2. Can you please send me a link to the **complete** "skin.estuary.mod" too?
I'm still using it.

**Pull request closed without merging**
