### PR TITLE
banner view: adjust width of watched/viewed label

### PR DESCRIPTION
**Pull request by mgonzales71**
banner view: adjust width of watched/viewed label

sending a PR in case you agree with minor width adjustment 

see before/after:

kodi_2018-04-17_08-13-05

### CODE REVIEW

**Comment by Guilouz** [comment]
Need some other adjustments. But I have fixed this.

**Comment by mgonzales71** [comment]
Oh, forgot to mention that you may need to re-adjust again....
I think #### / #### 4 digits of episodes is plenty of space to reserve.

Tested with your changes still getting clipped/scrolling text:

kodi_2018-04-21_09-23-22
 
I am thinking adjusting respective widths to say 570->590 and 140->150 should do it.

**Comment by mgonzales71** [comment]
kodi_2018-04-21_09-30-53

FYI - did a test (see above) with the following changes (from my off the cuff suggested adjustments):

https://pastebin.com/PR9Wk68C

**Comment by Guilouz** [comment]
Working for me with width to 140 but I have set width to 150 in last git.

**Comment by mgonzales71** [comment]
just grabbed update from your commit and looks good.  hopefully some tv show doesn't get 10000+ episodes lol

**Pull request closed without merging**
