### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by kukharski**
I see *.DS_Store in every folder of Estuary.Mod, when i update Kodi skin from repo :)

### CODE REVIEW

**Comment by Guilouz** [comment]
There is no DS_Store on my repo.

**Comment by kukharski** [comment]
ok, but .DS_Store is here again
in this skin in every update by Kodi…

**Comment by Guilouz** [comment]
Looks all folders in git, there is no DS_Store files.

**Comment by kukharski** [comment]
for example - repository.guilouz/_repo/skin.estuary.mod/skin.estuary.mod-1.7.1.zip - in this zip .DS_Store in every folder…

**Pull request closed without merging**
